## Shared libraries
usr/lib/openmpi/lib/libmca_common_sm.so.3.0.1
usr/lib/openmpi/lib/libmpi_cxx.so.1.0.2
usr/lib/openmpi/lib/libmpi_f77.so.1.0.7
usr/lib/openmpi/lib/libmpi_f90.so.1.3.0
usr/lib/openmpi/lib/libmpi.so.1.0.8
usr/lib/openmpi/lib/libompitrace.so.0.0.0
usr/lib/openmpi/lib/libopen-pal.so.4.0.5
usr/lib/openmpi/lib/libopen-rte.so.4.0.3
## Plugins
usr/lib/openmpi/lib/openmpi/*.so
## Other files
usr/lib/openmpi/lib/mpi.mod
